var oracledb = require('oracledb');
require('dotenv').config();

// DB_HOST, DB_PORT, DB_SERVICE_NAME 으로 전체 DESCRIPTION 연결 문자열 조합
// ORA-12504 (SERVICE_NAME 누락 오류) 방지
function buildConnectString() {
  var host    = process.env.DB_HOST || 'localhost';
  var port    = process.env.DB_PORT || '1521';
  var svcName = process.env.DB_SERVICE_NAME || process.env.DB_NAME || 'ORCL';
  return '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=' + host + ')(PORT=' + port + '))(CONNECT_DATA=(SERVICE_NAME=' + svcName + ')))';
}

async function init() {
  var conn;
  try {
    // 1. DB 접속 정보 확인
    var dbConfig = {
      user:          process.env.DB_USER,
      password:      process.env.DB_PASS || process.env.DB_PASSWORD || '',
      connectString: buildConnectString()
    };

    conn = await oracledb.getConnection(dbConfig);
    console.log("DB 접속 성공! 테이블 생성을 시작합니다.");

    // 2. 기존 테이블 삭제 (초기화용 - 필요 없으면 삭제하세요)
    try { await conn.execute(`DROP TABLE Applications`); } catch (e) {}
    try { await conn.execute(`DROP TABLE Employees`); } catch (e) {}

    // 3. 직원 정보 테이블 생성
    await conn.execute(`
      CREATE TABLE Employees (
        emp_id VARCHAR2(50) PRIMARY KEY,
        password VARCHAR2(255),
        agency VARCHAR2(100),
        dept VARCHAR2(100),
        phone VARCHAR2(20)
      )
    `);
    console.log("Employees 테이블 생성 완료.");

    // 4. 예약 신청 테이블 생성 (v10/구형 오라클 호환 문법)
    // IDENTITY 문법에서 에러가 나면 시퀀스로 대체해야 할 수도 있습니다.
    await conn.execute(`
      CREATE TABLE Applications (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        applicant_id VARCHAR2(50),
        room_name VARCHAR2(50),
        start_date DATE,
        end_date DATE,
        status VARCHAR2(20)
      )
    `);
    console.log("Applications 테이블 생성 완료.");

    // 5. 확정 저장
    await conn.commit();
    console.log("모든 변경사항이 저장되었습니다.");

  } catch (err) {
    console.error("오류 발생 상세 정보:");
    console.error("메시지:", err.message);
    // env 값이 제대로 읽혔는지 확인 (보안 주의: 비밀번호는 제외)
    console.error("접속 정보 요약:", process.env.DB_USER, "@", process.env.DB_HOST);
  } finally {
    if (conn) {
      try {
        await conn.close();
        console.log("DB 연결 종료.");
      } catch (err) {
        console.error("연결 종료 중 오류:", err.message);
      }
    }
  }
}

init();